#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-logging-parent
Version  : 1
Release  : 1
URL      : https://github.com/apache/logging-parent/archive/logging-parent-1.tar.gz
Source0  : https://github.com/apache/logging-parent/archive/logging-parent-1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/logging/logging-parent/1/logging-parent-1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-logging-parent-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-logging-parent package.
Group: Data

%description data
data components for the mvn-logging-parent package.


%prep
%setup -q -n logging-parent-logging-parent-1

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/logging-parent/1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/logging-parent/1/logging-parent-1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/logging/logging-parent/1/logging-parent-1.pom
